USE customer_behavior;
SELECT * FROM customer limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?
Select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more money than average purchase amounts?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG (purchase_amount) FROM customer);


 -- Q3 Which are the top 5 products with the hights average review rating?
 DESCRIBE customer;
 
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4  Campare the avg purchase amount between standard and express shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customer spenfd more? campare average spend and total revenue between subcribers and non-subcribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc;


-- Q6. Which 5 product have the hightest percentage of purchase with discount applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2 ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

-- Q7. Segment customer into new, returning, and loytal based on their total number of previous purchase, and show the count of each segment.

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'NEW'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

SELECT customer_segment, count(*) as "Number odf customer"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased product within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


--  Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT  age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

    

